frontend:
    resource: "@frontendBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@adminBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

getregion:
    path: /ville/{idc}
    defaults: { _controller : adminBundle:Registration:region}